# Add source files here
EXECUTABLE	:= CUSTOM1

# CUDA source files (compiled with cudacc)
CUFILES		:= benchGPU.cu

# CUDA dependency files
CU_DEPS		:=

# C/C++ source files (compiled with gcc / c++)
CCFILES		:= main.cpp

#CUDACCFLAGS     := -po maxrregcount=16

include ../common/common.mk
